#region Set variables
event_inherited();
Mentality = "Range";
Style = choose("Brute","Finisher");
ChaseStyle = choose("Go max","Go min");
RevengeEntity = noone;
RevengeTime = 0;
Target = noone;
DownButtonPressedActive = false;
LeftButtonPressedActive = false;
RightButtonPressedActive = false;
JumpButtonActive = false;
JumpButtonReleaseActive = false;
AttackButtonPressedActive = false;
DownButtonReleasedActive = false;
DownButtonActive = false;
AttackButtonActive = false;
AttackButtonReleasedActive = false;
UpButtonActive = false;
UpButtonReleasedActive = false;
UpButtonPressedActive = false;
JumpButtonPressedActive = false;
LeftButtonActive = false;
RightButtonActive = false;
StartButtonReleasedActive = false;
SelectButtonReleasedActive = false;
SetColor = true;
Target = noone;
Mode = "Avoid";
HoldLeftButton = 0;
HoldRightButton = 0;
HoldDownButton = 0;
HoldUpButton = 0;
HoldAttackButton = 0;
HoldJumpButton = 0;
ListRecover = ds_list_create();
ds_list_add(ListRecover , "Aerial Down" , "Aerial Up");
ListRecoverActual = ds_list_create();
LastMov = "";
MarioCooldownRecover = 0;
#endregion